// Auto-generated by generate-db-types.ts
// Do not edit manually!

export interface Role {
  id: number;
  name: string;
  created_at: Date;
  updated_at: Date;
}

export interface RolePermission {
  role_id: number;
  permission_id: number;
}

export interface Permission {
  id: number;
  action: string;
  subject: string;
  created_at: Date;
  updated_at: Date;
}

export interface Customer {
  id: number;
  name: string;
  email: string | null;
  phone: string | null;
  cpf: string | null;
  address: string | null;
  loyalty_points: number | null;
  store_credit_balance: number | null;
  deleted_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface User {
  id: string;
  name: string;
  email: string;
  password_hash: string;
  customer_id: number | null;
  branch_id: number | null;
  role: string | null;
  theme_preference: string | null;
  xp: number | null;
  level: number | null;
  failed_login_attempts: number;
  last_login: Date | null;
  deleted_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface Branche {
  id: number;
  name: string;
  address: string | null;
  phone: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface UserRole {
  user_id: string;
  role_id: number;
}

export interface ProductsHistory {
  history_id: number;
  product_id: number;
  name: string | null;
  description: string | null;
  category_id: number | null;
  sku: string | null;
  is_serialized: boolean | null;
  price: number | null;
  changed_at: Date;
  changed_by: string | null;
  change_type: string;
  snapshot: any | null;
}

export interface StockHistory {
  history_id: number;
  product_variation_id: number;
  branch_id: number;
  old_quantity: number | null;
  new_quantity: number;
  reason: string | null;
  reference_id: string | null;
  changed_at: Date;
  changed_by: string | null;
}

export interface AuditLog {
  id: number;
  user_id: string | null;
  action: string;
  entity_type: string | null;
  entity_id: string | null;
  details: any | null;
  ip_address: string | null;
  created_at: Date;
}

export interface StoreCreditTransaction {
  id: number;
  customer_id: number;
  amount: number;
  type: string;
  related_id: number | null;
  reason: string | null;
  created_at: Date;
}

export interface Lead {
  id: number;
  name: string;
  email: string;
  phone: string | null;
  source: string | null;
  status: string;
  assigned_to: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface LeadActivitie {
  id: number;
  lead_id: number;
  activity_type: string;
  description: string | null;
  activity_date: Date;
  user_id: string | null;
  created_at: Date;
}

export interface FeatureFlag {
  id: number;
  name: string;
  description: string | null;
  is_enabled: boolean;
  rules: any | null;
  updated_at: Date;
  created_at: Date;
}

export interface Categorie {
  id: number;
  name: string;
  description: string | null;
  parent_id: number | null;
  icon: string | null;
  color: string | null;
  slug: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface Product {
  id: number;
  name: string;
  description: string | null;
  branch_id: number | null;
  category_id: number | null;
  sku: string | null;
  product_type: string;
  is_serialized: boolean | null;
  deleted_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface ProductVariation {
  id: number;
  product_id: number;
  name: string | null;
  sku: string | null;
  color: string | null;
  price: number;
  cost_price: number | null;
  low_stock_threshold: number | null;
  reorder_point: number | null;
  lead_time_days: number | null;
  deleted_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface BranchProductVariationsStock {
  branch_id: number;
  product_variation_id: number;
  stock_quantity: number;
  min_stock_level: number | null;
  created_at: Date;
  updated_at: Date;
}

export interface ProductStock {
  product_variation_id: number;
  branch_id: number;
  quantity: number;
}

export interface InventoryMovement {
  id: number;
  product_variation_id: number;
  branch_id: number;
  quantity_change: number;
  reason: string;
  user_id: string | null;
  unit_cost: number | null;
  quantity_remaining: number | null;
  created_at: Date;
}

export interface Part {
  id: number;
  name: string;
  sku: string | null;
  stock_quantity: number | null;
  low_stock_threshold: number | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface PartSupplier {
  part_id: number;
  supplier_id: number;
  cost: number;
}

export interface Supplier {
  id: number;
  name: string;
  contact_info: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface ChecklistTemplate {
  id: number;
  name: string;
  type: string | null;
  created_at: Date | null;
  updated_at: Date;
}

export interface ChecklistTemplateItem {
  id: number;
  template_id: number;
  item_name: string;
  position: number | null;
}

export interface PrintJob {
  id: number;
  customer_name: string;
  customer_phone: string | null;
  description: string;
  quantity: number;
  status: string;
  created_at: Date;
  updated_at: Date;
}

export interface Sale {
  id: number;
  user_id: string | null;
  customer_id: number | null;
  branch_id: number | null;
  total_amount: number;
  external_order_id: string | null;
  marketplace_integration_id: number | null;
  status: string | null;
  sale_date: Date;
  updated_at: Date;
}

export interface SaleItem {
  id: number;
  sale_id: number;
  product_id: number | null;
  variation_id: number | null;
  quantity: number;
  unit_price: number;
  cost_price: number;
  total_price: number;
  metadata: any | null;
}

export interface SalePayment {
  id: number;
  sale_id: number;
  payment_method: string;
  amount: number;
  transaction_details: any | null;
  created_at: Date | null;
}

export interface Discount {
  id: number;
  name: string;
  type: string;
  value: number;
  start_date: Date;
  end_date: Date | null;
  is_active: boolean | null;
  min_purchase_amount: number | null;
  max_uses: number | null;
  uses_count: number | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface Return {
  id: number;
  sale_id: number;
  reason: string | null;
  status: string | null;
  refund_amount: number;
  refund_method: string | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface ReturnItem {
  id: number;
  return_id: number | null;
  sale_item_id: number | null;
  variation_id: number | null;
  quantity: number;
  condition: string | null;
  inspection_status: string | null;
  inspection_notes: string | null;
  inspected_by: string | null;
  inspected_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface Notification {
  id: number;
  user_id: string | null;
  title: string;
  message: string;
  type: string | null;
  priority: string | null;
  read: boolean | null;
  link: string | null;
  metadata: any | null;
  created_at: Date;
}

export interface ServiceOrder {
  id: number;
  customer_id: number | null;
  branch_id: number | null;
  user_id: string | null;
  product_description: string;
  brand: string | null;
  imei: string | null;
  device_password: string | null;
  issue_description: string;
  services: any | null;
  observations: string | null;
  down_payment: number | null;
  part_quality: string | null;
  audio_url: string | null;
  expected_delivery_date: Date | null;
  last_status_update: Date | null;
  status: string | null;
  priority: string | null;
  estimated_cost: number | null;
  final_cost: number | null;
  entry_date: Date | null;
  delivery_date: Date | null;
  public_token: string | null;
  customer_approval_status: string | null;
  customer_approval_date: Date | null;
  entry_checklist: any | null;
  notes: string | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface ServiceOrderStatusHistory {
  id: number;
  service_order_id: number;
  old_status: string | null;
  new_status: string;
  changed_by_user_id: string | null;
  changed_at: Date;
}

export interface ServiceOrderItem {
  id: number;
  service_order_id: number;
  part_id: number | null;
  service_description: string | null;
  quantity: number;
  unit_price: number;
  created_at: Date;
}

export interface ServiceOrderAttachment {
  id: number;
  service_order_id: number;
  file_path: string;
  file_type: string;
  description: string | null;
  uploaded_by_user_id: string | null;
  uploaded_at: Date;
}

export interface ServiceOrderComment {
  id: number;
  service_order_id: number;
  user_id: string;
  comment_text: string;
  created_at: Date;
}

export interface DiagnosticNode {
  id: number;
  question_text: string;
  is_solution: boolean | null;
  solution_details: string | null;
  parent_node_id: number | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface DiagnosticNodeOption {
  id: number;
  diagnostic_node_id: number;
  option_text: string;
  next_node_id: number | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface DiagnosticFeedback {
  id: number;
  node_id: number | null;
  user_id: string | null;
  is_helpful: boolean | null;
  comments: string | null;
  created_at: Date | null;
}

export interface DiagnosticHistory {
  id: number;
  user_id: string | null;
  session_id: string;
  node_id: number;
  selected_option_id: number | null;
  action: string | null;
  created_at: Date | null;
}

export interface ExpenseReimbursement {
  id: number;
  user_id: string;
  branch_id: number | null;
  amount: number;
  description: string;
  status: string | null;
  approved_by: string | null;
  rejection_reason: string | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface PurchaseOrder {
  id: number;
  supplier_id: number | null;
  branch_id: number | null;
  status: string | null;
  total_amount: number | null;
  notes: string | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface PurchaseOrderItem {
  id: number;
  purchase_order_id: number;
  product_variation_id: number | null;
  quantity: number;
  unit_price: number;
  created_at: Date | null;
}

export interface AccountsPayable {
  id: number;
  supplier_id: number | null;
  branch_id: number | null;
  description: string;
  amount: number;
  due_date: Date;
  status: string | null;
  paid_date: Date | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface AccountsReceivable {
  id: number;
  customer_id: number | null;
  branch_id: number | null;
  description: string;
  amount: number;
  due_date: Date;
  status: string | null;
  received_date: Date | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface WhatsappTemplate {
  id: number;
  name: string;
  content: string;
  is_active: boolean | null;
  created_at: Date;
  updated_at: Date;
}

export interface WhatsappLog {
  id: number;
  customer_id: number | null;
  phone: string;
  content: string;
  status: string | null;
  error_message: string | null;
  sent_at: Date | null;
  created_at: Date | null;
}

export interface MarketplaceConfig {
  id: number;
  name: string;
  api_key: string | null;
  api_secret: string | null;
  access_token: string | null;
  refresh_token: string | null;
  token_expires_at: Date | null;
  is_active: boolean | null;
  created_at: Date;
  updated_at: Date;
}

export interface MarketplaceListing {
  id: number;
  marketplace_id: number | null;
  product_variation_id: number | null;
  external_id: string;
  external_url: string | null;
  status: string | null;
  last_synced_at: Date | null;
  sync_error: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface PricingRule {
  id: number;
  name: string;
  condition_type: string;
  condition_value: any;
  action_type: string;
  action_value: number;
  is_active: boolean | null;
  priority: number | null;
  created_at: Date;
  updated_at: Date;
}

export interface PriceHistory {
  id: number;
  variation_id: number | null;
  old_price: number;
  new_price: number;
  reason: string | null;
  changed_by: string | null;
  created_at: Date | null;
}

export interface KanbanCard {
  id: number;
  column_id: number | null;
  title: string;
  description: string | null;
  priority: string | null;
  due_date: Date | null;
  position: number;
  tags: any | null;
  assignees: any | null;
  service_order_id: number | null;
  created_at: Date | null;
  updated_at: Date | null;
  assignee_id: string | null;
}

export interface KanbanColumn {
  id: number;
  title: string;
  position: number;
  is_system: boolean | null;
  wip_limit: number | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface ActivityFeed {
  id: number;
  user_id: string;
  branch_id: number | null;
  activity_type: string;
  activity_data: any | null;
  created_at: Date;
}

export interface UserChallengeProgres {
  user_id: string;
  challenge_id: number;
  current_value: number | null;
  completed: boolean | null;
  completed_at: Date | null;
}

export interface GamificationChallenge {
  id: number;
  title: string;
  description: string | null;
  metric: string;
  target_value: number;
  reward_xp: number;
  start_date: Date;
  end_date: Date;
  created_at: Date | null;
}

export interface UserBadge {
  user_id: string;
  badge_id: number;
  awarded_at: Date | null;
}

export interface Badge {
  id: number;
  name: string;
  description: string | null;
  icon_url: string | null;
  metric: string | null;
  threshold: number | null;
  created_at: Date | null;
}

export interface Coupon {
  id: number;
  code: string;
  type: string;
  value: number;
  start_date: Date;
  end_date: Date | null;
  min_purchase_amount: number | null;
  max_uses: number | null;
  uses_count: number;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface Referral {
  id: number;
  referrer_customer_id: number;
  referred_customer_id: number | null;
  referral_code: string;
  status: string;
  completed_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface LoyaltyTier {
  id: number;
  name: string;
  min_points: number;
  description: string | null;
  benefits: any | null;
  created_at: Date;
  updated_at: Date;
}

export interface LoyaltyTransaction {
  id: number;
  customer_id: number;
  points: number;
  type: string;
  reason: string | null;
  created_at: Date;
}

export interface Automation {
  id: number;
  name: string;
  trigger_type: string;
  trigger_config: any | null;
  is_active: boolean | null;
  created_at: Date;
  updated_at: Date;
}

export interface AutomationStep {
  id: number;
  automation_id: number;
  type: string;
  payload: any | null;
  order_index: number;
}

export interface AutomationRun {
  id: number;
  automation_id: number;
  customer_id: number;
  status: string;
  current_step: number;
  trigger_payload: any | null;
  next_step_due_at: Date;
  created_at: Date;
  updated_at: Date;
}

export interface ProductKit {
  id: number;
  name: string;
  description: string | null;
  price: number;
  image_url: string | null;
  tags: any | null;
  is_active: boolean | null;
  created_at: Date;
  updated_at: Date;
}

export interface ProductKitItem {
  id: number;
  kit_id: number;
  product_id: number;
  variation_id: number;
  quantity: number;
}

export interface TimeClockEntrie {
  id: number;
  user_id: string;
  branch_id: number;
  clock_in_time: Date;
  clock_out_time: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface TaskTimeLog {
  id: number;
  user_id: string;
  service_order_id: number;
  start_time: Date;
  end_time: Date | null;
  notes: string | null;
  created_at: Date;
}

export interface QuarantineItem {
  id: number;
  product_id: number | null;
  variation_id: number | null;
  supplier_id: number | null;
  service_order_id: number | null;
  quantity: number;
  reason: string;
  defect_details: string | null;
  physical_location: string | null;
  is_battery_risk: boolean | null;
  warranty_expiry_date: Date | null;
  item_cost: number | null;
  status: string;
  identified_by: string | null;
  rma_tracking_code: string | null;
  image_url: string | null;
  video_url: string | null;
  audio_url: string | null;
  signature_url: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface SatisfactionSurvey {
  id: number;
  service_order_id: number | null;
  customer_id: number | null;
  technician_id: string | null;
  rating_overall: number;
  rating_technical: number | null;
  rating_service: number | null;
  rating_price: number | null;
  comment: string | null;
  internal_notes: string | null;
  store_response: string | null;
  response_time_seconds: number | null;
  sentiment_score: string | null;
  ai_topics: any | null;
  customer_loyalty_level: string | null;
  is_public: boolean | null;
  images: any | null;
  created_at: Date;
  updated_at: Date;
}

export interface SystemBranding {
  id: number;
  franchise_id: string | null;
  logo_url: string | null;
  primary_color: string | null;
  secondary_color: string | null;
  font_family: string | null;
  favicon_url: string | null;
  app_name: string | null;
  updated_at: Date;
}

export interface Tag {
  id: number;
  name: string;
  color: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface ProductCompatibilitie {
  id: number;
  brand: string;
  model: string;
  compatible_models: any;
  category: string;
  notes: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface StockTransfer {
  id: number;
  from_branch_id: number;
  to_branch_id: number;
  status: string;
  sent_at: Date | null;
  received_at: Date | null;
  created_at: Date;
  updated_at: Date;
}

export interface StockTransferItem {
  id: number;
  transfer_id: number;
  product_variation_id: number;
  quantity: number;
}

export interface RefreshToken {
  id: number;
  user_id: string;
  token: string;
  expires_at: Date;
  created_at: Date;
}
