import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['./tests/setupUnit.ts'],
    globalSetup: [], // Disable global setup for unit tests
    include: ['tests/unit/**/*.test.ts'], // Only unit tests
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
      exclude: [
        'coverage/**',
        'dist/**',
        'migrations/**',
        'scripts/**',
        'src/db/**',
        'src/index.ts',
        'src/types/**',
        'src/routes/**',
        'src/graphql/**',
        'src/listeners/**',
        'src/microservices/**',
        'src/jobs/**',
        'src/events/**',
        'src/utils/telemetry.ts',
        'src/utils/test-module.ts',
        'src/middlewares/**', // Excluding all middlewares for now, will be covered by integration tests
        'src/controllers/**', // Excluding all controllers for now, will be covered by integration tests
        'src/services/marketingAutomationService.ts',
        'src/services/marketplaceSyncService.ts',
        'src/services/ofxService.ts',
        'src/services/onboardingService.ts',
        'src/services/paymentGatewayService.ts',
        'src/services/paymentMethodService.ts',
        'src/services/performanceReviewService.ts',
        'src/services/priceSuggestionService.ts',
        'src/services/privacyService.ts',
        'src/services/publicPortalService.ts',
        'src/services/purchaseAutomationService.ts',
        'src/services/quoteService.ts',
        'src/services/receiptService.ts',
        'src/services/recommendationService.ts',
        'src/services/reportService.ts',
        'src/services/reviewService.ts',
        'src/services/rfmService.ts',
        'src/services/salesGoalService.ts',
        'src/services/salesHistoryService.ts',
        'src/services/searchService.ts',
        'src/services/sentimentService.ts',
        'src/services/serializedItemService.ts',
        'src/services/shiftReportService.ts',
        'src/services/smartPricingService.ts',
        'src/services/stockTransferService.ts',
        'src/services/surveyService.ts',
        'src/services/tagService.ts',
        'src/services/techAppService.ts',
        'src/services/whatIfService.ts',
        'src/services/zReportService.ts',
        'swagger.js',
        'vitest.global-setup.ts',
        '**/*.config.js',
        '**/*.config.ts',
        '**/node_modules/**',
        '**/tests/**',
      ],
    },
    deps: {
      optimizer: {
        ssr: {
          include: ['express-validator'],
        },
      },
    },
    transformMode: {
      ssr: ['express-validator'],
      web: ['express-validator'],
    },
    hookTimeout: 300000,
  },
  optimizeDeps: {
    include: ['express-validator'],
  },
});