import pkg from 'pg';
const { Client } = pkg;
import fs from 'fs';
import path from 'path';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL || 'postgresql://postgres:aj13ime1@localhost:5432/pdv_web';

const typeMap: Record<string, string> = {
  'integer': 'number',
  'bigint': 'string',
  'numeric': 'number',
  'decimal': 'number',
  'real': 'number',
  'double precision': 'number',
  'smallint': 'number',
  'boolean': 'boolean',
  'text': 'string',
  'character varying': 'string',
  'varchar': 'string',
  'character': 'string',
  'uuid': 'string',
  'timestamp': 'Date',
  'timestamp with time zone': 'Date',
  'timestamp without time zone': 'Date',
  'date': 'Date',
  'json': 'any',
  'jsonb': 'any',
};

async function generate() {
  const client = new Client({ connectionString });
  await client.connect();

  console.log('Connected to database. Fetching schema...');

  const tablesQuery = `
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
    AND table_name NOT LIKE 'pg_%' AND table_name NOT LIKE 'sql_%';
  `;

  const { rows: tables } = await client.query(tablesQuery);
  let output = `// Auto-generated by generate-db-types.ts
// Do not edit manually!

`;

  for (const table of tables) {
    const tableName = table.table_name;
    const columnsQuery = `
      SELECT column_name, data_type, is_nullable
      FROM information_schema.columns
      WHERE table_name = $1
      ORDER BY ordinal_position;
    `;
    const { rows: columns } = await client.query(columnsQuery, [tableName]);

    const interfaceName = tableName
      .split('_')
      .map((part: string) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
      .replace(/s$/, ''); // Basic singularization

    output += `export interface ${interfaceName} {
`;
    for (const col of columns) {
      const tsType = typeMap[col.data_type] || 'any';
      const isNullable = col.is_nullable === 'YES' ? ' | null' : '';
      output += `  ${col.column_name}: ${tsType}${isNullable};
`;
    }
    output += `}

`;
  }

  const outputPath = path.resolve('src/types/database.types.ts');
  fs.writeFileSync(outputPath, output);
  console.log(`Generated types for ${tables.length} tables at ${outputPath}`);

  await client.end();
}

generate().catch(console.error);
